vich_uploader:
    db_driver: orm

    mappings:
        pdf_files:
            uri_prefix: /uploads/supports/
            upload_destination: '%kernel.project_dir%/public/uploads/supports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
